### ISSUE TITLE
Better explain Insight3 usage

### ISSUE THREAD

**Issue by stefanotorresi** [CosmaLab/CLUSTER_ANALYSIS_main#5]
If I understood correctly, these lines needs to be commented out and changed based on how one wants to use the `Insight3` class.
https://github.com/CosmaLab/CLUSTER_ANALYSIS_main/blob/d34b23df11046064023c8a3a8cdf1ebc35eb4f49/Insight3.m#L3-L13

This is very unclear, could you please clarify this with further doc blocks?

Cheers.

**Comment by LauraM947** [comment]
Hi Stefano, sorry for the delay in answering, we hadn't seen the Issue notification
We've just updated the code with more instructions
These lines are examples of operations you can do with Insight3 function
For example, to read a specific .bin file you just have to copy-paste in the Command Window the line
i3 = Insight3('D:/sample.bin'); 
modifying the 'D:/sample.bin' with the correct .bin file address

**Comment by stefanotorresi** [comment]
Thanks for the update! It's much clearer now that those were examples and not meant to be uncommented inline.
